const COMMON_FOODS = [
    // Fruit
    { name: "Apple", carbs: 14.0 },
    { name: "Banana", carbs: 23.0 },
    { name: "Orange", carbs: 12.0 },
    { name: "Grapes", carbs: 17.0 },
    { name: "Mango", carbs: 15.0 },
    { name: "Pineapple", carbs: 13.0 },
    { name: "Strawberries", carbs: 8.0 },
    { name: "Blueberries", carbs: 14.0 },
    { name: "Watermelon", carbs: 8.0 },
    { name: "Pear", carbs: 15.0 },
    { name: "Peach", carbs: 10.0 },
    { name: "Cherries", carbs: 16.0 },
    { name: "Raspberries", carbs: 12.0 },
    { name: "Kiwi", carbs: 15.0 },
    { name: "Melon", carbs: 8.0 },
    { name: "Plum", carbs: 11.0 },
    // Vegetables (starchy)
    { name: "Potato (boiled)", carbs: 17.0 },
    { name: "Potato (baked)", carbs: 21.0 },
    { name: "Sweet potato", carbs: 20.0 },
    { name: "Chips / French fries", carbs: 35.0 },
    { name: "Corn / Sweetcorn", carbs: 19.0 },
    { name: "Peas", carbs: 14.0 },
    { name: "Parsnip", carbs: 13.0 },
    // Bread & bakery
    { name: "White bread", carbs: 49.0 },
    { name: "Brown bread", carbs: 44.0 },
    { name: "Wholegrain bread", carbs: 41.0 },
    { name: "Bagel", carbs: 53.0 },
    { name: "Croissant", carbs: 46.0 },
    { name: "Pitta bread", carbs: 55.0 },
    { name: "Naan bread", carbs: 50.0 },
    { name: "Tortilla wrap (flour)", carbs: 52.0 },
    { name: "Crumpet", carbs: 40.0 },
    { name: "English muffin", carbs: 47.0 },
    // Grains & pasta
    { name: "White rice (cooked)", carbs: 28.0 },
    { name: "Brown rice (cooked)", carbs: 23.0 },
    { name: "Pasta (cooked)", carbs: 25.0 },
    { name: "Spaghetti (cooked)", carbs: 25.0 },
    { name: "Noodles (cooked)", carbs: 24.0 },
    { name: "Couscous (cooked)", carbs: 23.0 },
    { name: "Oats (dry)", carbs: 66.0 },
    { name: "Porridge (with water)", carbs: 12.0 },
    { name: "Quinoa (cooked)", carbs: 21.0 },
    // Cereals
    { name: "Cornflakes", carbs: 84.0 },
    { name: "Weetabix", carbs: 69.0 },
    { name: "Muesli", carbs: 66.0 },
    { name: "Granola", carbs: 64.0 },
    { name: "Bran flakes", carbs: 67.0 },
    // Dairy
    { name: "Milk (whole)", carbs: 4.7 },
    { name: "Milk (semi-skimmed)", carbs: 4.8 },
    { name: "Yogurt (plain)", carbs: 7.0 },
    { name: "Yogurt (flavoured)", carbs: 15.0 },
    { name: "Greek yogurt", carbs: 4.0 },
    { name: "Ice cream (vanilla)", carbs: 24.0 },
    // Drinks
    { name: "Orange juice", carbs: 10.0 },
    { name: "Apple juice", carbs: 11.0 },
    { name: "Coca-Cola", carbs: 11.0 },
    { name: "Lucozade Sport", carbs: 6.4 },
    { name: "Ribena (diluted)", carbs: 5.0 },
    { name: "Smoothie (fruit)", carbs: 13.0 },
    { name: "Beer (pint ~568ml)", carbs: 13.0 },
    { name: "Wine (glass ~175ml)", carbs: 2.0 },
    // Snacks & sweets
    { name: "Chocolate (milk)", carbs: 57.0 },
    { name: "Chocolate (dark)", carbs: 46.0 },
    { name: "Crisps / Potato chips", carbs: 53.0 },
    { name: "Digestive biscuit", carbs: 67.0 },
    { name: "Rich Tea biscuit", carbs: 74.0 },
    { name: "Flapjack", carbs: 60.0 },
    { name: "Doughnut", carbs: 48.0 },
    { name: "Muffin (blueberry)", carbs: 51.0 },
    { name: "Cereal bar", carbs: 64.0 },
    { name: "Jelly babies", carbs: 77.0 },
    { name: "Glucose tablets", carbs: 95.0 },
    // Legumes
    { name: "Baked beans", carbs: 15.0 },
    { name: "Lentils (cooked)", carbs: 20.0 },
    { name: "Chickpeas (cooked)", carbs: 27.0 },
    // Fast food / meals
    { name: "Pizza (cheese, per slice)", carbs: 30.0 },
    { name: "Burger bun", carbs: 50.0 },
    { name: "Fish and chips (portion)", carbs: 30.0 },
];
